# Generated by Django 4.1.1 on 2023-02-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bdds_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="location",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
