# Generated by Django 4.1.1 on 2023-02-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bdds_dashboard", "0002_location_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Jurisdiction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jurisdiction",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
    ]
