# Generated by Django 4.1.1 on 2023-02-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bdds_dashboard", "0010_designation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dispose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dispose", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
