# Generated by Django 4.1.1 on 2023-02-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bdds_dashboard", "0011_dispose"),
    ]

    operations = [
        migrations.CreateModel(
            name="Logine_creation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("mnumber", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "ldesignation",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=256, null=True)),
                ("password", models.CharField(max_length=50)),
            ],
        ),
    ]
