# Generated by Django 4.1.1 on 2023-02-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bdds_dashboard", "0012_logine_creation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logine_creation",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="logine_creation",
            name="password",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
