# Generated by Django 4.1.1 on 2023-02-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bdds_dashboard", "0013_alter_logine_creation_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Form_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fbomb", models.CharField(blank=True, max_length=200, null=True)),
                ("fdate", models.CharField(blank=True, max_length=200, null=True)),
                ("flocation", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "flocation_type",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("flocation_description", models.TextField(blank=True, null=True)),
                (
                    "fjuridiction",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("fincident", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "fweight_data",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("fexplosive", models.CharField(blank=True, max_length=200, null=True)),
                ("fdetonator", models.CharField(blank=True, max_length=200, null=True)),
                ("fswitch", models.CharField(blank=True, max_length=200, null=True)),
                ("ftarget", models.CharField(blank=True, max_length=200, null=True)),
                ("fdeath", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "fdistruction",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("fassume", models.CharField(blank=True, max_length=200, null=True)),
                ("radio_data", models.CharField(blank=True, max_length=200, null=True)),
                ("fdalam", models.CharField(blank=True, max_length=200, null=True)),
                ("flearning", models.CharField(blank=True, max_length=200, null=True)),
                ("finjured", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "fassume_status",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
    ]
