# Generated by Django 4.1.1 on 2023-02-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bdds_dashboard", "0014_form_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="form_data",
            name="fserial",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
