# Generated by Django 4.1.1 on 2023-02-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bdds_dashboard", "0015_form_data_fserial"),
    ]

    operations = [
        migrations.AddField(
            model_name="form_data",
            name="incident_image",
            field=models.ImageField(blank=True, null=True, upload_to="incident_image"),
        ),
        migrations.AddField(
            model_name="form_data",
            name="sketch_image",
            field=models.ImageField(blank=True, null=True, upload_to="sketch_image"),
        ),
        migrations.AddField(
            model_name="form_data",
            name="special_report",
            field=models.ImageField(blank=True, null=True, upload_to="special_report"),
        ),
    ]
