# Generated by Django 4.1.1 on 2023-02-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bdds_dashboard",
            "0016_form_data_incident_image_form_data_sketch_image_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Dalam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dalam", models.CharField(blank=True, max_length=200, null=True)),
                ("d_time", models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
