# Generated by Django 4.1.1 on 2023-02-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bdds_dashboard", "0017_dalam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dalam",
            name="d_time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
