# Generated by Django 4.1.1 on 2023-02-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bdds_dashboard",
            "0019_cstatus_c_time_designation_d_time_detection_d_time_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="sp_logine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sname", models.CharField(blank=True, max_length=200, null=True)),
                ("snumber", models.IntegerField(blank=True, null=True)),
                (
                    "sdesignation",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("semail", models.EmailField(blank=True, max_length=256, null=True)),
                ("spassword", models.CharField(blank=True, max_length=200, null=True)),
                ("s_time", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
