# Generated by Django 4.1.1 on 2023-02-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bdds_dashboard", "0020_sp_logine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sp_logine",
            name="snumber",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
