# Generated by Django 4.1.1 on 2023-02-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bdds_dashboard", "0021_alter_sp_logine_snumber"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nlogines_creations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lname", models.CharField(blank=True, max_length=200, null=True)),
                ("l_numbers", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "l_designation",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("l_email", models.EmailField(blank=True, max_length=256, null=True)),
                (
                    "l_password",
                    models.EmailField(blank=True, max_length=256, null=True),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Cstatus",
        ),
        migrations.DeleteModel(
            name="Dalam",
        ),
        migrations.DeleteModel(
            name="Designation",
        ),
        migrations.DeleteModel(
            name="Detection",
        ),
        migrations.DeleteModel(
            name="Dispose",
        ),
        migrations.DeleteModel(
            name="Explosive",
        ),
        migrations.DeleteModel(
            name="Form_data",
        ),
        migrations.DeleteModel(
            name="Incident",
        ),
        migrations.DeleteModel(
            name="Jurisdiction",
        ),
        migrations.DeleteModel(
            name="Location",
        ),
        migrations.DeleteModel(
            name="Logine_creation",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.DeleteModel(
            name="sp_logine",
        ),
        migrations.DeleteModel(
            name="Weight",
        ),
    ]
