# Generated by Django 4.1.1 on 2023-02-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bdds_dashboard",
            "0022_nlogines_creations_delete_cstatus_delete_dalam_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="nlogines_creations",
            old_name="lname",
            new_name="l_name",
        ),
        migrations.AddField(
            model_name="nlogines_creations",
            name="l_datetime",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="nlogines_creations",
            name="l_password",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
