# Generated by Django 4.1.1 on 2023-02-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bdds_dashboard", "0023_rename_lname_nlogines_creations_l_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="N_degignation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "d_designation",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("d_datetime", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Nsp_authourity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("s_name", models.CharField(blank=True, max_length=200, null=True)),
                ("s_numbers", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "s_designation",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("s_email", models.EmailField(blank=True, max_length=256, null=True)),
                ("s_password", models.CharField(blank=True, max_length=200, null=True)),
                ("s_datetime", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
