# Generated by Django 4.1.1 on 2023-02-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bdds_dashboard", "0024_n_degignation_nsp_authourity"),
    ]

    operations = [
        migrations.CreateModel(
            name="N_juridiction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "l_juridiction",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("l_datetime", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="N_location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("l_location", models.CharField(blank=True, max_length=200, null=True)),
                ("l_datetime", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
