# Generated by Django 4.1.1 on 2023-02-09 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "bdds_dashboard",
            "0026_dalam_n_assused_n_dispose_n_ditection_n_explosive_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="dalam",
            new_name="N_dalam",
        ),
    ]
