# Generated by Django 4.1.1 on 2023-02-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bdds_dashboard", "0027_rename_dalam_n_dalam"),
    ]

    operations = [
        migrations.CreateModel(
            name="Form_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fserial", models.CharField(blank=True, max_length=200, null=True)),
                ("d_bomb", models.CharField(blank=True, max_length=200, null=True)),
                ("fdate", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
