# Generated by Django 4.1.1 on 2023-02-11 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bdds_dashboard", "0029_form_data_fassume_form_data_fassume_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="injured_person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "injured_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "injured_contact",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "form_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bdds_dashboard.form_data",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo_video",
                    models.ImageField(upload_to="E:\\Gadcchiroli_BDDS\\images\\image1"),
                ),
                (
                    "special_report",
                    models.ImageField(upload_to="E:\\Gadcchiroli_BDDS\\images\\image2"),
                ),
                (
                    "sketch_scence",
                    models.ImageField(upload_to="E:\\Gadcchiroli_BDDS\\images\\image3"),
                ),
                ("status_code", models.IntegerField()),
                (
                    "form_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bdds_dashboard.form_data",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="exploded",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exploded_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "explode_contact",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "form_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bdds_dashboard.form_data",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="death_person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("death_name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "death_contact",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "form_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bdds_dashboard.form_data",
                    ),
                ),
            ],
        ),
    ]
