# Generated by Django 4.1.1 on 2023-02-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bdds_dashboard", "0030_injured_person_images_exploded_death_person"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="form_data",
            name="fassume_status",
        ),
        migrations.RemoveField(
            model_name="form_data",
            name="fdeath",
        ),
        migrations.RemoveField(
            model_name="form_data",
            name="finjured",
        ),
        migrations.AddField(
            model_name="form_data",
            name="detected_description",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="form_data",
            name="dispose_contact",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="form_data",
            name="mode_of_detection",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
