# Generated by Django 4.1.1 on 2023-02-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bdds_dashboard", "0031_remove_form_data_fassume_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="form_data",
            name="detcted_contact",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="form_data",
            name="detected_dispose",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="form_data",
            name="detected_pname",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="form_data",
            name="dispose_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="form_data",
            name="fassume_status_new",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
