# Generated by Django 4.1.1 on 2023-02-13 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "bdds_dashboard",
            "0032_form_data_detcted_contact_form_data_detected_dispose_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="death_person",
            old_name="form_id",
            new_name="form",
        ),
    ]
