# Generated by Django 4.1.1 on 2023-02-13 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bdds_dashboard", "0033_rename_form_id_death_person_form"),
    ]

    operations = [
        migrations.RenameField(
            model_name="injured_person",
            old_name="form_id",
            new_name="form",
        ),
    ]
