# Generated by Django 4.1.1 on 2023-02-13 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bdds_dashboard", "0034_rename_form_id_injured_person_form"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exploded",
            old_name="form_id",
            new_name="form",
        ),
    ]
