# Generated by Django 4.1.1 on 2023-02-13 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bdds_dashboard", "0035_rename_form_id_exploded_form"),
    ]

    operations = [
        migrations.RenameField(
            model_name="images",
            old_name="form_id",
            new_name="form",
        ),
        migrations.RemoveField(
            model_name="images",
            name="sketch_scence",
        ),
        migrations.RemoveField(
            model_name="images",
            name="special_report",
        ),
        migrations.RemoveField(
            model_name="images",
            name="status_code",
        ),
        migrations.CreateModel(
            name="sk_report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sketch_scence",
                    models.ImageField(upload_to="E:\\Gadcchiroli_BDDS\\images\\image3"),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bdds_dashboard.form_data",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="s_report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "special_report",
                    models.ImageField(upload_to="E:\\Gadcchiroli_BDDS\\images\\image2"),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bdds_dashboard.form_data",
                    ),
                ),
            ],
        ),
    ]
