# Generated by Django 4.1.1 on 2023-02-13 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bdds_dashboard", "0036_rename_form_id_images_form_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="images",
            old_name="photo_video",
            new_name="im_vi",
        ),
    ]
