# Generated by Django 4.1.1 on 2023-02-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bdds_dashboard", "0037_rename_photo_video_images_im_vi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="im_vi",
            field=models.ImageField(upload_to="E:/Gadcchiroli_BDDS/images/image1"),
        ),
        migrations.AlterField(
            model_name="s_report",
            name="special_report",
            field=models.ImageField(upload_to="E:/Gadcchiroli_BDDS/images/image2"),
        ),
        migrations.AlterField(
            model_name="sk_report",
            name="sketch_scence",
            field=models.ImageField(upload_to="E:/Gadcchiroli_BDDS/images/image3"),
        ),
    ]
