# Generated by Django 4.1.1 on 2023-02-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bdds_dashboard",
            "0039_alter_images_im_vi_alter_s_report_special_report_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="im_vi",
            field=models.ImageField(upload_to="incident_image/"),
        ),
        migrations.AlterField(
            model_name="s_report",
            name="special_report",
            field=models.ImageField(upload_to="sketch_image/"),
        ),
        migrations.AlterField(
            model_name="sk_report",
            name="sketch_scence",
            field=models.ImageField(upload_to="special_report/"),
        ),
    ]
