# Generated by Django 4.1.1 on 2023-02-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bdds_dashboard",
            "0040_alter_images_im_vi_alter_s_report_special_report_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="im_vi",
            field=models.ImageField(blank=True, null=True, upload_to="image1/"),
        ),
        migrations.AlterField(
            model_name="s_report",
            name="special_report",
            field=models.ImageField(blank=True, null=True, upload_to="image2/"),
        ),
        migrations.AlterField(
            model_name="sk_report",
            name="sketch_scence",
            field=models.ImageField(blank=True, null=True, upload_to="image3/"),
        ),
    ]
