# Generated by Django 4.1.1 on 2023-02-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bdds_dashboard",
            "0041_alter_images_im_vi_alter_s_report_special_report_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="images",
            name="status",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
