# Generated by Django 4.1.1 on 2023-02-23 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bdds_dashboard", "0042_images_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="nlogines_creations",
            old_name="l_name",
            new_name="permission_delete",
        ),
        migrations.RenameField(
            model_name="nlogines_creations",
            old_name="l_password",
            new_name="permission_edit",
        ),
        migrations.RemoveField(
            model_name="nlogines_creations",
            name="l_email",
        ),
        migrations.AddField(
            model_name="nlogines_creations",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
