# Generated by Django 4.1.1 on 2023-02-23 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "bdds_dashboard",
            "0043_rename_l_name_nlogines_creations_permission_delete_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="nlogines_creations",
            name="user",
            field=models.OneToOneField(
                default=12,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
