# Generated by Django 4.1.1 on 2023-02-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bdds_dashboard", "0044_alter_nlogines_creations_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nlogines_creations",
            name="permission_delete",
            field=models.IntegerField(blank=True, default=0, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="nlogines_creations",
            name="permission_edit",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
