# Generated by Django 4.1.1 on 2023-02-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bdds_dashboard", "0046_alter_nlogines_creations_permission_delete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nlogines_creations",
            name="permission_delete",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="nlogines_creations",
            name="permission_edit",
            field=models.IntegerField(default=0),
        ),
    ]
