# Generated by Django 4.1.1 on 2023-02-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bdds_dashboard", "0050_alter_nlogines_creations_permission_delete_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nlogines_creations",
            name="permission_delete",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="nlogines_creations",
            name="permission_edit",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
