# Generated by Django 4.1.1 on 2023-02-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bdds_dashboard", "0054_alter_nlogines_creations_permission_delete_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nlogines_creations",
            name="permission_delete",
            field=models.IntegerField(blank=True, default="0", null=True),
        ),
        migrations.AlterField(
            model_name="nlogines_creations",
            name="permission_edit",
            field=models.IntegerField(blank=True, default="0", null=True),
        ),
    ]
