# Generated by Django 4.1.1 on 2023-02-24 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bdds_dashboard", "0055_alter_nlogines_creations_permission_delete_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nlogines_creations",
            name="l_datetime",
        ),
        migrations.AddField(
            model_name="nlogines_creations",
            name="join_designation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bdds_dashboard.n_degignation",
            ),
        ),
    ]
