# Generated by Django 4.1.1 on 2023-02-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bdds_dashboard", "0056_remove_nlogines_creations_l_datetime_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nlogines_creations",
            name="join_designation",
        ),
        migrations.AddField(
            model_name="form_data",
            name="delete_request",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="form_data",
            name="edit_request",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
