# Generated by Django 4.1.1 on 2023-03-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bdds_dashboard", "0058_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="images",
            name="sketch_scences",
            field=models.ImageField(blank=True, null=True, upload_to="image3/"),
        ),
        migrations.AddField(
            model_name="images",
            name="special_reports",
            field=models.ImageField(blank=True, null=True, upload_to="image2/"),
        ),
    ]
