# Generated by Django 4.1.1 on 2023-03-08 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bdds_dashboard", "0059_images_sketch_scences_images_special_reports"),
    ]

    operations = [
        migrations.RenameField(
            model_name="death_person",
            old_name="form",
            new_name="form_id",
        ),
        migrations.RenameField(
            model_name="exploded",
            old_name="form",
            new_name="form_id",
        ),
        migrations.RenameField(
            model_name="images",
            old_name="form",
            new_name="form_id",
        ),
        migrations.RenameField(
            model_name="injured_person",
            old_name="form",
            new_name="form_id",
        ),
        migrations.RenameField(
            model_name="s_report",
            old_name="form",
            new_name="form_id",
        ),
        migrations.RenameField(
            model_name="sk_report",
            old_name="form",
            new_name="form_id",
        ),
        migrations.RemoveField(
            model_name="images",
            name="sketch_scences",
        ),
        migrations.RemoveField(
            model_name="images",
            name="special_reports",
        ),
    ]
