# Generated by Django 4.1.1 on 2023-03-08 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bdds_dashboard", "0060_rename_form_death_person_form_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="death_person",
            old_name="form_id",
            new_name="form",
        ),
        migrations.RenameField(
            model_name="exploded",
            old_name="form_id",
            new_name="form",
        ),
        migrations.RenameField(
            model_name="images",
            old_name="form_id",
            new_name="form",
        ),
        migrations.RenameField(
            model_name="injured_person",
            old_name="form_id",
            new_name="form",
        ),
        migrations.RenameField(
            model_name="s_report",
            old_name="form_id",
            new_name="form",
        ),
        migrations.RenameField(
            model_name="sk_report",
            old_name="form_id",
            new_name="form",
        ),
    ]
