# Generated by Django 4.1.1 on 2023-03-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bdds_dashboard", "0061_rename_form_id_death_person_form_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="form_data",
            name="user_id",
            field=models.IntegerField(null=True),
        ),
    ]
