# Generated by Django 4.1.1 on 2023-03-11 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bdds_dashboard", "0062_form_data_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="nlogines_creations",
            name="join_designation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bdds_dashboard.n_degignation",
            ),
        ),
    ]
