# Generated by Django 4.1.1 on 2023-03-11 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bdds_dashboard", "0063_nlogines_creations_join_designation"),
    ]

    operations = [
        migrations.AddField(
            model_name="nlogines_creations",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bdds_dashboard.n_post",
            ),
        ),
    ]
