# Generated by Django 4.1.1 on 2023-03-12 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bdds_dashboard", "0065_alter_form_data_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="form_data",
            name="user_id",
        ),
        migrations.AddField(
            model_name="form_data",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bdds_dashboard.n_post",
            ),
        ),
    ]
