# Generated by Django 4.1.1 on 2023-03-24 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bdds_dashboard", "0067_alter_form_data_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form_data",
            name="fassume",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="form_data",
            name="fdistruction",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="form_data",
            name="flearning",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="form_data",
            name="flocation_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="form_data",
            name="fswitch",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="form_data",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
