# Generated by Django 4.1.1 on 2023-03-24 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "bdds_dashboard",
            "0068_alter_form_data_fassume_alter_form_data_fdistruction_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="form_data",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
