# Generated by Django 4.1.1 on 2023-03-24 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bdds_dashboard", "0069_alter_form_data_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nlogines_creations",
            name="join_designation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bdds_dashboard.n_degignation",
            ),
        ),
        migrations.AlterField(
            model_name="nlogines_creations",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bdds_dashboard.n_post",
            ),
        ),
    ]
