# Generated by Django 4.2.6 on 2023-10-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdds_dashboard', '0070_alter_nlogines_creations_join_designation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='video_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images')),
                ('video', models.FileField(upload_to='video')),
            ],
        ),
    ]
