# Generated by Django 4.2.6 on 2023-10-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdds_dashboard', '0071_video_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_image',
            name='images',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='video_image',
            name='video',
            field=models.FileField(upload_to='video/'),
        ),
    ]
