# Generated by Django 4.2.6 on 2023-10-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdds_dashboard', '0072_alter_video_image_images_alter_video_image_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='im_vi',
            field=models.ImageField(blank=True, null=True, upload_to='file/image1/'),
        ),
        migrations.AlterField(
            model_name='s_report',
            name='special_report',
            field=models.ImageField(blank=True, null=True, upload_to='file/image2/'),
        ),
        migrations.AlterField(
            model_name='sk_report',
            name='sketch_scence',
            field=models.ImageField(blank=True, null=True, upload_to='file/image3/'),
        ),
    ]
