# Generated by Django 4.2.6 on 2023-10-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdds_dashboard', '0073_alter_images_im_vi_alter_s_report_special_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='im_vi',
            field=models.FileField(blank=True, null=True, upload_to='file/image1/'),
        ),
    ]
