# Generated by Django 4.2.6 on 2023-10-17 11:07

import bdds_dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdds_dashboard', '0074_alter_images_im_vi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='im_vi',
            field=models.FileField(blank=True, null=True, upload_to=bdds_dashboard.models.image_upload_to),
        ),
        migrations.AlterField(
            model_name='s_report',
            name='special_report',
            field=models.FileField(blank=True, null=True, upload_to='file/image2/'),
        ),
    ]
