# Generated by Django 4.2.6 on 2023-10-17 12:06

import bdds_dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdds_dashboard', '0075_alter_images_im_vi_alter_s_report_special_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s_report',
            name='special_report',
            field=models.FileField(blank=True, null=True, upload_to=bdds_dashboard.models.pdf_upload_to),
        ),
        migrations.AlterField(
            model_name='sk_report',
            name='sketch_scence',
            field=models.ImageField(blank=True, null=True, upload_to=bdds_dashboard.models.sketch_upload_to),
        ),
    ]
