# Generated by Django 4.2.1 on 2023-10-27 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bdds_dashboard', '0077_alter_form_data_fdalam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_data',
            name='flocation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bdds_dashboard.n_location'),
        ),
    ]
