# Generated by Django 4.2.1 on 2023-10-27 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bdds_dashboard', '0078_alter_form_data_flocation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_data',
            name='fassume_status_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bdds_dashboard.n_assused'),
        ),
        migrations.AlterField(
            model_name='form_data',
            name='fincident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bdds_dashboard.n_incident'),
        ),
        migrations.AlterField(
            model_name='form_data',
            name='fjuridiction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bdds_dashboard.n_juridiction'),
        ),
        migrations.AlterField(
            model_name='form_data',
            name='fweight_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bdds_dashboard.n_weight'),
        ),
    ]
