# Generated by Django 4.2.1 on 2023-10-27 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bdds_dashboard', '0080_alter_form_data_fexplosive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_data',
            name='detected_dispose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bdds_dashboard.n_dispose'),
        ),
        migrations.AlterField(
            model_name='form_data',
            name='mode_of_detection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bdds_dashboard.n_ditection'),
        ),
    ]
