# Generated by Django 5.2.11 on 2026-02-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bdds_dashboard", "0081_alter_form_data_detected_dispose_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="form_data",
            name="fir",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="form_data",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="form_data",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=12, null=True
            ),
        ),
        migrations.RemoveField(
            model_name="form_data",
            name="fdalam",
        ),
        migrations.AddField(
            model_name="form_data",
            name="fdalam",
            field=models.ManyToManyField(blank=True, to="bdds_dashboard.n_dalam"),
        ),
    ]
