# Generated by Django 5.2.11 on 2026-02-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bdds_dashboard",
            "0082_form_data_fir_form_data_latitude_form_data_longitude_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="form_data",
            name="fdate",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
